net: squash: revert nf_conntrack_pptp for build
/root/project/out/../net/netfilter/nf_conntrack_pptp.c:416: undefined reference to `pptp_msg_name'
/root/project/out/../net/netfilter/nf_conntrack_pptp.c:416:(.text+0x6aa34): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `pptp_msg_name'
/root/project/out/../net/netfilter/nf_conntrack_pptp.c:438: undefined reference to `pptp_msg_name'
...

This reverts commit f89fd706a6bf22e28d8e11b8c67fabc6b9df69e3.
This reverts commit fff122956d7ac379e36e50f8d2520a90daefb3b5.

Signed-off-by: fadlyas07 <fadlyardhians@gmail.com>
Change-Id: I511cc66b4391f896fe6829ba72b89833ed5ab146